# Generated by Django 5.1.6 on 2025-02-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.vendingmachine')),
            ],
        ),
    ]
