# Generated by Django 5.1.6 on 2025-02-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('machines', '0002_alter_vendingmachine_location'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='vending_machine',
        ),
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='machines.location'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MachineRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_added', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.vendingmachine')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_refills', to='visits.visit')),
            ],
        ),
    ]
