# Generated by Django 5.1.6 on 2025-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_visit_vending_machine_visit_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_visited',
            field=models.DateTimeField(),
        ),
    ]
