# Generated by Django 4.2.19 on 2025-02-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_alter_visit_date_visited"),
    ]

    operations = [
        migrations.RemoveField(model_name="machinerefill", name="units_added",),
        migrations.AddField(
            model_name="machinerefill",
            name="quantity_added",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machinerefill",
            name="quantity_observed",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machinerefill",
            name="quantity_withdrawn",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machinerefill",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refills",
                to="visits.visit",
            ),
        ),
    ]
