# Generated by Django 4.2.19 on 2025-02-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0002_alter_vendingmachine_location"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="address",),
        migrations.RemoveField(model_name="vendingmachine", name="last_visited",),
        migrations.AddField(
            model_name="location",
            name="address_1",
            field=models.CharField(default="2351 Douglas Rd", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(default="Miami", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="last_visited",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(default="FL", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
