# Generated by Django 4.2 on 2025-05-17 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("Snack", "Snack"),
                            ("Soda", "Soda"),
                            ("Combo", "Combo"),
                        ],
                        max_length=100,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MachineItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "slot",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="Numeric slot position in the machine",
                        null=True,
                    ),
                ),
                ("current_stock", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("Soda", "Soda"), ("Snack", "Snack")],
                        db_index=True,
                        default="Soda",
                        max_length=20,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(blank=True, default="unit", max_length=50),
                ),
                ("image_url", models.URLField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="core.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WholesalePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchased_at", models.DateTimeField()),
                ("supplier", models.CharField(blank=True, default="", max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wholesale_purchases",
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitMachineRestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restocks",
                        to="core.machine",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_restocks",
                        to="core.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_before", models.IntegerField()),
                ("discarded", models.IntegerField(default=0)),
                ("restocked", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_entries",
                        to="core.product",
                    ),
                ),
                (
                    "visit_machine_restock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_entries",
                        to="core.visitmachinerestock",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "product_type"], name="core_produc_name_634efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="core_produc_created_182d27_idx"
            ),
        ),
        migrations.AddField(
            model_name="machineitemprice",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_prices",
                to="core.machine",
            ),
        ),
        migrations.AddField(
            model_name="machineitemprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_prices",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machines",
                to="core.location",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitmachinerestock", unique_together={("visit", "machine")},
        ),
        migrations.AddIndex(
            model_name="machineitemprice",
            index=models.Index(
                fields=["machine", "product"], name="core_machin_machine_ff6abd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machineitemprice",
            index=models.Index(
                fields=["machine", "slot"], name="core_machin_machine_f65473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machineitemprice",
            index=models.Index(fields=["price"], name="core_machin_price_252f3d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="machineitemprice", unique_together={("machine", "product")},
        ),
    ]
