# Generated by Django 4.2 on 2025-05-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Current quantity in inventory"
            ),
        ),
        migrations.AddField(
            model_name="wholesalepurchase",
            name="inventory_updated",
            field=models.BooleanField(
                default=False, help_text="Flag to track if inventory has been updated"
            ),
        ),
        migrations.CreateModel(
            name="ProductCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_history",
                        to="core.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to="core.wholesalepurchase",
                    ),
                ),
            ],
            options={"ordering": ["-date"],},
        ),
        migrations.AddIndex(
            model_name="productcost",
            index=models.Index(
                fields=["product", "-date"], name="core_produc_product_ade151_idx"
            ),
        ),
    ]
