# Generated by Django 4.2.20 on 2025-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.CharField(blank=True, help_text='Route designation for restocking planning', max_length=50, null=True),
        ),
    ]
