# Generated by Django 4.2 on 2025-07-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_route_to_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock_after_restock', models.IntegerField(help_text='Stock level after previous restock')),
                ('current_stock_before_restock', models.IntegerField(help_text='Stock level before current restock')),
                ('days_between_visits', models.IntegerField(help_text='Number of days between visits')),
                ('total_consumption', models.IntegerField(help_text='Total units consumed between visits')),
                ('daily_demand', models.DecimalField(decimal_places=2, help_text='Average daily demand', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_records_current', to='core.visit')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_records', to='core.machine')),
                ('previous_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_records_previous', to='core.visit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_records', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demandtracking',
            index=models.Index(fields=['machine', 'product'], name='core_demand_machine_ad0acc_idx'),
        ),
        migrations.AddIndex(
            model_name='demandtracking',
            index=models.Index(fields=['current_visit'], name='core_demand_current_b48a4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandtracking',
            unique_together={('machine', 'product', 'current_visit')},
        ),
    ]
