# Generated by Django 4.2 on 2025-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_image_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, default='unit', max_length=50),
        ),
    ]
