# Generated by Django 4.2.20 on 2025-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_supplier_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalepurchase',
            name='supplier_name',
            field=models.CharField(blank=True, default='', help_text='Legacy supplier name field for backward compatibility', max_length=100),
        ),
    ] 