# Generated by Django 4.2 on 2025-03-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Soda', 'Soda'), ('Snack', 'Snack')], default='Soda', max_length=20),
        ),
    ]
