# Generated by Django 4.2 on 2025-03-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wholesalepurchase",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wholesalepurchase",
            name="supplier",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
