# Generated by Django 4.2.20 on 2025-07-07 14:16

from django.db import migrations


def migrate_supplier_data(apps, schema_editor):
    """
    Migrate existing supplier data:
    1. Copy supplier string values to supplier_name field
    2. Create supplier records and map them to purchases
    """
    WholesalePurchase = apps.get_model('core', 'WholesalePurchase')
    Supplier = apps.get_model('core', 'Supplier')
    
    # Get all existing purchases
    purchases = WholesalePurchase.objects.all()
    
    # Create mapping of supplier names to supplier objects
    supplier_mapping = {}
    
    # Process each purchase
    for purchase in purchases:
        # Get the original supplier name
        original_supplier = purchase.supplier.strip() if purchase.supplier else ''
        
        # Set the supplier_name field (for backward compatibility)
        purchase.supplier_name = original_supplier
        
        # Determine the supplier to use
        if original_supplier:
            supplier_name = original_supplier
        else:
            supplier_name = 'Unknown Supplier'
        
        # Create or get the supplier
        if supplier_name not in supplier_mapping:
            supplier, created = Supplier.objects.get_or_create(
                name=supplier_name,
                defaults={
                    'is_active': True,
                    'notes': 'Migrated from legacy data' if original_supplier else 'Default supplier for empty entries'
                }
            )
            supplier_mapping[supplier_name] = supplier
        
        # Save the purchase with updated supplier_name
        purchase.save()
    
    # Create some default suppliers
    default_suppliers = [
        {'name': 'Sams Club', 'notes': 'Default supplier - Sams Club'},
        {'name': 'Walmart', 'notes': 'Default supplier - Walmart'},
        {'name': 'Costco', 'notes': 'Default supplier - Costco'},
    ]
    
    for supplier_data in default_suppliers:
        Supplier.objects.get_or_create(
            name=supplier_data['name'],
            defaults={
                'is_active': True,
                'notes': supplier_data['notes']
            }
        )


def reverse_migrate_supplier_data(apps, schema_editor):
    """
    Reverse migration - remove supplier_name data
    """
    WholesalePurchase = apps.get_model('core', 'WholesalePurchase')
    
    # Clear supplier_name field
    WholesalePurchase.objects.update(supplier_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_supplier_name_field'),
    ]

    operations = [
        migrations.RunPython(
            migrate_supplier_data,
            reverse_migrate_supplier_data,
        ),
    ] 