# Generated by Django 4.2 on 2025-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wholesalepurchase_notes_wholesalepurchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockentry',
            name='discarded',
            field=models.IntegerField(default=0),
        ),
    ]
