# Generated by Django 4.2 on 2025-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restockentry_discarded'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineitemprice',
            unique_together={('machine', 'product')},
        ),
        migrations.AddField(
            model_name='machineitemprice',
            name='slot',
            field=models.PositiveIntegerField(default=1, help_text='Numeric slot position in the machine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Soda', 'Soda'), ('Snack', 'Snack')], db_index=True, default='Soda', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='machineitemprice',
            unique_together={('machine', 'product'), ('machine', 'slot')},
        ),
        migrations.AddIndex(
            model_name='machineitemprice',
            index=models.Index(fields=['machine', 'product'], name='core_machin_machine_ff6abd_idx'),
        ),
        migrations.AddIndex(
            model_name='machineitemprice',
            index=models.Index(fields=['machine', 'slot'], name='core_machin_machine_f65473_idx'),
        ),
        migrations.AddIndex(
            model_name='machineitemprice',
            index=models.Index(fields=['price'], name='core_machin_price_252f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'product_type'], name='core_produc_name_634efc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='core_produc_created_182d27_idx'),
        ),
    ]
