# Generated by Django 4.2 on 2025-04-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_assign_unique_slots'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineitemprice',
            unique_together={('machine', 'product')},
        ),
    ]
