# Generated by Django 4.2 on 2025-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_machineitemprice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineitemprice',
            name='slot',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Numeric slot position in the machine', null=True),
        ),
    ]
