# Generated by Django 4.2 on 2025-04-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_duplicate_slots'),
    ]

    operations = [
        # Explicitly remove the unique constraint for (machine, slot)
        migrations.RunSQL(
            # Forward SQL - Drop the constraint/index if it exists
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'core_machineitemprice_machine_id_slot_92f64367_uniq'
                ) THEN
                    ALTER TABLE core_machineitemprice 
                    DROP CONSTRAINT core_machineitemprice_machine_id_slot_92f64367_uniq;
                ELSIF EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = 'core_machineitemprice_machine_id_slot_92f64367_uniq'
                ) THEN
                    DROP INDEX core_machineitemprice_machine_id_slot_92f64367_uniq;
                END IF;
            END
            $$;
            """,
            # Reverse SQL (do nothing)
            "SELECT 1;"
        ),

        # Also explicitly alter unique_together to match the model's definition
        migrations.AlterUniqueTogether(
            name='machineitemprice',
            unique_together={('machine', 'product')},
        ),
    ]
